In [7]:
#Dependencies
import os
import pandas as pd

In [2]:
# List all files in Stocks folder
files = os.listdir("Stocks")

In [10]:
# Read all files in Stocks folder into dataframes and append them to list and add Ticker Name column
df_list = []

for f in files:
    try:
        df_list.append(pd.read_csv(f"Stocks/{f}").assign(ticker_name = f.split(sep=".")[0]))
        
    except: 
        print(f)

accp.us.txt
amrh.us.txt
amrhw.us.txt
asns.us.txt
bbrx.us.txt
bolt.us.txt
boxl.us.txt
bxg.us.txt
ehr.us.txt
fmax.us.txt
gnst.us.txt
hayu.us.txt
jt.us.txt
mapi.us.txt
molc.us.txt
otg.us.txt
pbio.us.txt
pxus.us.txt
rbio.us.txt
sail.us.txt
sbt.us.txt
scci.us.txt
scph.us.txt
send.us.txt
sfix.us.txt
srva.us.txt
stnl.us.txt
vist.us.txt
vmet.us.txt
wnfm.us.txt
wspt.us.txt
znwaa.us.txt

In [12]:
# Combine all my DataFrames
df= pd.concat(df_list)

In [13]:
df

,Date,Open,High,Low,Close,Volume,OpenInt,ticker_name
0,1999-11-18,30.7130,33.7540,27.0020,29.702,66277506,0,a
1,1999-11-19,28.9860,29.0270,26.8720,27.257,16142920,0,a
2,1999-11-22,27.8860,29.7020,27.0440,29.702,6970266,0,a
3,1999-11-23,28.6880,29.4460,27.0020,27.002,6332082,0,a
4,1999-11-24,27.0830,28.3090,27.0020,27.717,5132147,0,a
5,1999-11-26,27.5940,28.0120,27.5090,27.807,1832635,0,a
6,1999-11-29,27.6760,28.6500,27.3800,28.432,4317826,0,a
7,1999-11-30,28.3500,28.9860,27.6340,28.480,4567146,0,a
8,1999-12-01,28.4800,29.3240,28.2730,28.986,3133746,0,a
9,1999-12-02,29.5320,30.3750,29.1550,29.786,3252997,0,a
10,1999-12-03,30.3360,30.8420,29.9090,30.039,3223074,0,a
11,1999-12-06,30.5470,31.3480,30.5050,30.883,2385046,0,a
12,1999-12-07,30.8830,31.0520,29.9090,30.547,2348161,0,a
13,1999-12-08,30.5470,30.7950,30.2490,30.505,2000481,0,a
14,1999-12-09,30.5470,31.0120,30.5470,30.924,2150096,0,a
15,1999-12-10,30.8420,31.0120,30.2090,30.209,1764043,0,a
16,1999-12-13,30.7130,31.2210,29.9580,30.713,4260349,0,a
17,1999-12-14,30.6350,30.6350,28.3910,29.027,2467856,0,a
18,1999-12-15,28.3500,28.5610,27.6760,28.142,3091820,0,a
19,1999-12-16,28.3500,31.8960,28.3500,31.896,2738063,0,a
20,1999-12-17,31.3080,31.8080,30.6740,31.012,3929255,0,a
21,1999-12-20,31.2210,31.6870,31.1340,31.646,1268225,0,a
22,1999-12-21,31.5170,31.5170,31.0520,31.470,2394232,0,a
23,1999-12-22,31.4700,32.1040,31.2610,32.104,2019439,0,a
24,1999-12-23,32.0650,33.7540,32.0250,33.582,2288310,0,a
25,1999-12-27,33.7120,35.9060,33.4550,35.648,2150692,0,a
26,1999-12-28,36.6200,41.5140,36.4120,41.514,3772374,0,a
27,1999-12-29,42.5280,53.3690,42.4870,48.602,11146026,0,a
28,1999-12-30,51.3020,54.0030,50.1220,53.497,7069075,0,a
29,1999-12-31,53.6660,53.9660,51.4730,52.188,2046399,0,a
...,...,...,...,...,...,...,...,...
544,2017-10-02,8.8800,9.2700,8.3900,8.690,1829376,0,zyne
545,2017-10-03,8.9800,9.8000,8.7200,9.780,1863068,0,zyne
546,2017-10-04,10.0000,10.2600,9.5422,10.020,1275918,0,zyne
547,2017-10-05,10.0200,10.4485,10.0200,10.100,672628,0,zyne
548,2017-10-06,10.2000,10.3500,9.4500,9.660,726409,0,zyne
549,2017-10-09,9.6900,9.8500,9.2000,9.380,402038,0,zyne
550,2017-10-10,9.4500,10.1200,9.3801,9.950,635145,0,zyne
551,2017-10-11,10.1200,10.6400,9.9000,10.370,871267,0,zyne
552,2017-10-12,10.4500,10.4990,9.9200,10.060,420984,0,zyne
553,2017-10-13,10.1788,10.1788,9.5100,9.600,328513,0,zyne
554,2017-10-16,9.5600,9.7800,9.3100,9.470,287767,0,zyne
555,2017-10-17,9.3800,9.7600,9.0900,9.320,442331,0,zyne
556,2017-10-18,9.3300,9.4900,9.0900,9.390,198663,0,zyne
557,2017-10-19,9.6100,9.6900,9.2800,9.660,303491,0,zyne
558,2017-10-20,9.6500,9.8800,9.5250,9.730,299544,0,zyne
559,2017-10-23,9.7800,10.0600,9.6400,9.900,480391,0,zyne
560,2017-10-24,10.3700,10.5900,9.8510,10.050,586296,0,zyne
561,2017-10-25,10.0000,10.2000,9.8101,10.000,361461,0,zyne
562,2017-10-26,9.9500,9.9500,9.4100,9.500,294371,0,zyne
563,2017-10-27,9.4500,9.9300,9.4000,9.800,297751,0,zyne
564,2017-10-30,9.8000,10.2699,9.6300,9.760,256138,0,zyne
565,2017-10-31,9.7400,9.9492,9.6300,9.800,233242,0,zyne
566,2017-11-01,9.7000,9.9300,9.4100,9.690,301604,0,zyne
567,2017-11-02,9.5900,10.2000,9.5100,9.850,323496,0,zyne
568,2017-11-03,9.8300,10.5000,9.8300,10.330,531495,0,zyne
569,2017-11-06,10.4200,11.5400,10.4200,11.190,977948,0,zyne
570,2017-11-07,11.3000,11.4200,10.6700,10.830,451210,0,zyne
571,2017-11-08,10.7000,11.0600,10.3500,10.900,336449,0,zyne
572,2017-11-09,11.0000,11.8563,10.9700,11.600,463067,0,zyne
573,2017-11-10,11.6800,13.1500,11.3043,12.460,885587,0,zyne

In [16]:
df['Date'] = df['Date'].astype('datetime64[ns]')

In [8]:
import datetime as dt
interest_df = pd.read_csv("interest_rates/index.csv")

interest_df.head()

,Year,Month,Day,Federal Funds Target Rate,Federal Funds Upper Target,Federal Funds Lower Target,Effective Federal Funds Rate,Real GDP (Percent Change),Unemployment Rate,Inflation Rate
0,1954,7,1,NaN,NaN,NaN,0.80,4.6,5.8,NaN
1,1954,8,1,NaN,NaN,NaN,1.22,NaN,6.0,NaN
2,1954,9,1,NaN,NaN,NaN,1.06,NaN,6.1,NaN
3,1954,10,1,NaN,NaN,NaN,0.85,8.0,5.7,NaN
4,1954,11,1,NaN,NaN,NaN,0.83,NaN,5.3,NaN

Year                              int64
Month                             int64
Day                               int64
Federal Funds Target Rate       float64
Federal Funds Upper Target      float64
Federal Funds Lower Target      float64
Effective Federal Funds Rate    float64
Real GDP (Percent Change)       float64
Unemployment Rate               float64
Inflation Rate                  float64
dtype: object

In [22]:
year = interest_df.iloc[0,0]
month = interest_df.iloc[0,1]
day = interest_df.iloc[0,2]

In [25]:
dt.date(year, month, day)

datetime.date(1954, 7, 1)

In [29]:
interest_df["Date"]= interest_df.apply(lambda row: dt.date(int(row['Year']), int(row['Month']), int(row['Day'])), axis=1)

In [34]:

interest_df = interest_df[["Date", "Federal Funds Target Rate", "Federal Funds Upper Target", "Federal Funds Lower Target", "Effective Federal Funds Rate", "Real GDP (Percent Change)", "Unemployment Rate", "Inflation Rate"]]

interest_df.dtypes

Date                             object
Federal Funds Target Rate       float64
Federal Funds Upper Target      float64
Federal Funds Lower Target      float64
Effective Federal Funds Rate    float64
Real GDP (Percent Change)       float64
Unemployment Rate               float64
Inflation Rate                  float64
dtype: object

In [18]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:@207.151.52.40/ETL Project')

In [19]:
pd.read_sql("SELECT * FROM federal_interest_rate", engine)

OperationalError: (psycopg2.OperationalError) could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host "207.151.52.40" and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/e3q8)

In [ ]:
df.to_sql(stock_data, engine)